module.exports = [
    {
        path:'/store/delete',
        text:'删除了知识库'
    },
    {
        path:'/store/resetStoreItem',
        text:'编辑了知识库'
    },
    {
        path:'/store/createItem',
        text:'创建了知识库'
    },
    {
        path:'/doc/removeItem',
        text:'删除了文档'
    },
    {
        path:'/doc/resetItem',
        text:'编辑了文档'
    },
    {
        path:'/doc/createItem',
        text:'创建了文档'
    }
]